steps:
  # Step 1: Demonstrate Secret Manager integration
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "Accessing secret from Secret Manager"
        gcloud secrets versions access latest --secret=demo-secret

  # Step 2: Deployment placeholder (documented deployment)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deployment handled by Compute Engine VM runtime (pm2)"

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
