steps:
  # Step 1: Ensure target directory exists on VM
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="mkdir -p /home/arridz03_gmail_com/app"

  # Step 2: Copy source code to VM home directory
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute scp \
          --recurse . \
          ca1-vm:/home/arridz03_gmail_com/app \
          --zone=europe-west1-b \
          --quiet

  # Step 3: Deploy & run app
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="
            sudo rm -rf /var/www/app &&
            sudo mkdir -p /var/www/app &&
            sudo cp -r /home/arridz03_gmail_com/app/* /var/www/app/ &&
            sudo chown -R arridz03_gmail_com:arridz03_gmail_com /var/www/app &&

            export DEMO_SECRET=\$(gcloud secrets versions access latest --secret=demo-secret) &&
            gsutil cp gs://ca1vm-storage/test1.txt /var/www/app/test1.txt &&
            export TEST_FILE_PATH=/var/www/app/test1.txt &&

            cd /var/www/app &&
            npm install &&
            pm2 restart app --update-env || pm2 start index.js --name app
          "

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
