steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="
            export DEMO_SECRET=\$(gcloud secrets versions access latest --secret=demo-secret) &&
            gsutil cp gs://ca1vm-storage/test1.txt /var/www/app/test1.txt &&
            export TEST_FILE_PATH=/var/www/app/test1.txt &&
            cd /var/www/app &&
            git pull origin main &&
            npm install &&
            pm2 restart app --update-env
        "

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
