steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="
            sudo -u arridz03_gmail_com bash -c '
              set -e
              cd /var/www/app

              git pull origin main
              npm install

              export DEMO_SECRET=\$(gcloud secrets versions access latest --secret=demo-secret)

              gsutil cp gs://ca1vm-storage/test1.txt /var/www/app/demo.txt
              export TEST_FILE_PATH=/var/www/app/demo.txt

              pm2 delete app || true
              pm2 start index.js --name app --update-env
              pm2 save
            '
          "

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
