steps:
  # 1. Copy source code to VM (NO git)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="rm -rf /var/www/app/*"

        gcloud compute scp \
          --recurse . \
          ca1-vm:/var/www/app \
          --zone=europe-west1-b

  # 2. Run app with secrets & storage
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh ca1-vm \
          --zone=europe-west1-b \
          --quiet \
          --command="
            export DEMO_SECRET=\$(gcloud secrets versions access latest --secret=demo-secret) &&
            gsutil cp gs://ca1vm-storage/test1.txt /var/www/app/test1.txt &&
            export TEST_FILE_PATH=/var/www/app/test1.txt &&
            cd /var/www/app &&
            npm install &&
            pm2 restart app --update-env || pm2 start index.js --name app
          "

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
